/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Endpoint that serves Prometheus metrics.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint returning standardized APIResponse.
         *
         *     Args:
         *         deep: When True, probes Postgres, Redis, Qdrant, Ollama and the
         *             LangGraph checkpointer instead of only reporting that the process
         *             is up. Any failed dependency sets the HTTP status to 503 so
         *             uptime monitors and load balancers can act on it, not just read it.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate user credentials and issue access + refresh tokens.
         *
         *     Rate limit: max 5 requests per minute per IP.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Exchange a valid refresh token for a new access + refresh token pair.
         *
         *     Rate limit: max 20 requests per minute per IP.
         *     The refresh token is validated against:
         *     - JWT signature and expiry
         *     - Token type (must be 'refresh', not 'access')
         *     - Redis blacklist (invalidated on logout)
         *     - Active user status
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout the current user by blacklisting both access and refresh tokens in Redis.
         *
         *     Raises:
         *         BaseAppException: 500, if a token that was still live could not be
         *             blacklisted -- the caller must not be told logout succeeded when
         *             the token remains usable.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Chat Message
         * @description Orchestrate a chat interaction and return the completed result.
         *
         *     Routes the user input through the master planning graph, which resolves
         *     whether it needs analysis, drafting, document Q&A or plain conversation.
         *     May also return an ``INTERRUPTED`` status when the run paused at the
         *     human-in-the-loop gate; resume it via ``POST /chat/resume``.
         */
        post: operations["send_chat_message_api_v1_chat_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Chat Message
         * @description Orchestrate a chat interaction and stream progress events over SSE.
         *
         *     Emits ``session`` first with the resolved thread_id, then
         *     ``node_start``/``node_end``/``node_skipped``/``node_error`` for workflow
         *     phases, ``token`` for live text as it is generated, ``partial_result`` for
         *     intermediate output the client can render before the run finishes, and
         *     either a terminal ``final_result`` or, if the run paused at the
         *     human-in-the-loop gate, an ``interrupt`` event carrying what the human
         *     needs to answer.
         */
        post: operations["stream_chat_message_api_v1_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Chat Stream
         * @description Resume a run paused at the human-in-the-loop gate, streaming over SSE.
         *
         *     ``action="answer"`` fills in a draft's missing-information placeholders
         *     without regenerating it. ``action="approve"|"revise"|"reject"`` resolves a
         *     draft that needed a human's sign-off before unit routing.
         */
        post: operations["resume_chat_stream_api_v1_chat_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/resume/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Chat Sync
         * @description Resume a paused run and return the completed (or re-paused) result.
         */
        post: operations["resume_chat_sync_api_v1_chat_resume_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chat Sessions
         * @description List the caller's chat sessions, most recently active first.
         *
         *     ``user_id=None`` (``REQUIRE_AUTH`` off, or an ADMIN/MANAGER -- see
         *     ``bypasses_ownership``) lists every session, matching
         *     ``GET /documents``'s convention.
         */
        get: operations["list_chat_sessions_api_v1_chat_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chat Session Messages
         * @description List a session's messages in conversation order (oldest first).
         *
         *     Ownership reuses ``ChatService._verify_thread_ownership`` -- the same
         *     ``user_id:`` prefix check that already gates ``/chat/resume`` from
         *     touching another user's thread.
         *
         *     Raises:
         *         AuthorizationException: If ``session_id`` belongs to a different
         *             user than ``current_user``.
         */
        get: operations["list_chat_session_messages_api_v1_chat_sessions__session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session State
         * @description Report whether a session is idle, running, or paused on an interrupt.
         *
         *     Lets the client recover after a page reload or a dropped SSE connection:
         *     if ``status`` is ``"interrupted"``, re-render the resume form from the
         *     returned ``interrupt`` payload instead of losing it.
         */
        get: operations["get_session_state_api_v1_chat_sessions__session_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Document
         * @description Perform the first review (ön inceleme) of an incoming official document.
         *
         *     Reads the document via direct text extraction or OCR, determines its type,
         *     extracts its header fields, reports required-but-missing information with the
         *     relevant legislation, and returns a short summary.
         *
         *     Args:
         *         http_request: The raw request, checked for a declared Content-Length
         *             before the body is read at all.
         *         file: The uploaded document.
         *         service: Injected document analysis service.
         *         current_user: The authenticated caller, when ``REQUIRE_AUTH`` is on --
         *             registered as the document's owner so later reads can be
         *             restricted to it. ``None`` in the open demo/dev path.
         *
         *     Returns:
         *         The analysis result inside the unified success envelope.
         */
        post: operations["analyze_document_api_v1_documents_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Draft
         * @description Generate an official draft and department routing suggestion (Task 2).
         *
         *     Uses the output from the first review (Görev 1) to determine the correct
         *     correspondence type, draft the text, and route it to the appropriate department.
         *
         *     ``DraftService`` reads the source document straight from storage by
         *     ``storage_path`` -- unlike ``GET /documents/{storage_path}``, it has no
         *     ownership/clearance concept of its own, so that check belongs here, at
         *     the router boundary, before the raw file content ever reaches the
         *     drafting graph. ``current_user=None`` (``REQUIRE_AUTH`` disabled) skips
         *     it entirely, matching every other route in this router.
         *
         *     Raises:
         *         AuthorizationException: If the document belongs to a different
         *             owner than ``current_user`` (and it isn't an ADMIN/MANAGER), or
         *             ``current_user``'s clearance doesn't cover the document's
         *             confidentiality level.
         */
        post: operations["generate_draft_api_v1_documents_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description List uploaded documents with their summary metadata, newest first.
         *
         *     Args:
         *         pagination: Page/size query parameters.
         *         document_repository: Ownership/listing registry.
         *         current_user: The authenticated caller, when ``REQUIRE_AUTH`` is on --
         *             the list is restricted to documents it owns, unless it is an
         *             ADMIN/MANAGER (see ``bypasses_ownership``), who see every
         *             document company-wide the same as the open demo/dev path.
         *             ``None`` (``REQUIRE_AUTH`` off) also lists every document,
         *             matching today's behaviour.
         *
         *     Returns:
         *         A paginated envelope over the 7-field library projection (see
         *         ``GET /documents/{storage_path}`` for the full analysis).
         */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/correspondence-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Correspondence Types
         * @description List the supported outbound correspondence types and their Turkish labels.
         *
         *     Single source of truth for the frontend's type selector, instead of the
         *     labels being retyped in TypeScript and drifting from
         *     ``app.ai.workflows.correspondence.CORRESPONDENCE_TYPE_LABELS``.
         */
        get: operations["list_correspondence_types_api_v1_documents_correspondence_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{storage_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Analysis
         * @description Return a previously computed analysis in full.
         *
         *     ``GET /documents`` only ever returns the 7-field library projection
         *     (document_type_label, compliance_status, summary, ...); re-selecting a
         *     document from that list lost ``missing_fields`` and
         *     ``mevzuat_references`` entirely because nothing exposed the cached
         *     analysis this reads back.
         *
         *     Args:
         *         storage_path: The document's storage key (as returned by
         *             ``POST /documents/analyze``).
         *         service: Injected document analysis service.
         *         document_repository: Ownership registry, checked before returning
         *             content when a real user is attached to the request.
         *         current_user: The authenticated caller, when ``REQUIRE_AUTH`` is on.
         *             ``None`` in the open demo/dev path skips the ownership check
         *             entirely, matching today's behaviour.
         *
         *     Returns:
         *         The full analysis inside the unified success envelope.
         *
         *     Raises:
         *         HTTPException: 400 if storage_path is malformed, 404 if no analysis
         *             is cached for it.
         *         AuthorizationException: 403 if the document belongs to a different
         *             user than the one making the request, or the requester's
         *             clearance doesn't cover the document's confidentiality level.
         */
        get: operations["get_document_analysis_api_v1_documents__storage_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Drafts
         * @description List drafts, one row per session (its latest version), newest first.
         *
         *     ``session_id``/``document_id`` narrow the listing; ``user_id`` is
         *     resolved from the caller and is not a query parameter, same as
         *     ``GET /documents``/``GET /chat/sessions``.
         */
        get: operations["list_drafts_api_v1_drafts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Draft
         * @description Fetch one draft version by id.
         */
        get: operations["get_draft_api_v1_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drafts/{draft_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Draft Versions
         * @description List every version in this draft's revision chain, oldest first.
         */
        get: operations["list_draft_versions_api_v1_drafts__draft_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routing/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest Routing
         * @description Produce a unit-routing decision for a draft, independent of drafting it.
         *
         *     Standalone from ``POST /documents/draft`` so a human who edits a draft
         *     after it was generated can get a fresh routing decision without paying
         *     for a new generation -- the routing graph runs on the fast tier and reads
         *     only the draft text and its confidence score.
         */
        post: operations["suggest_routing_api_v1_routing_suggest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Retrieve multiple users with pagination and role filters (Admin/Manager only).
         */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /**
         * Register
         * @description Register a new user account in the system, validating the email invitation whitelist.
         */
        post: operations["register_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite User
         * @description Invite/whitelist an email address with a predefined role for registration (Admin/Manager only).
         */
        post: operations["invite_user_api_v1_users_invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Get profile details of the currently authenticated user.
         */
        get: operations["get_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User
         * @description Retrieve details of a specific user. Authenticated user can only retrieve themselves, unless they are Admin/Manager.
         */
        get: operations["get_user_api_v1_users__user_id__get"];
        /**
         * Update User
         * @description Update profile details of a user. Role or status changes require Admin privileges.
         */
        put: operations["update_user_api_v1_users__user_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change My Password
         * @description Update password of current logged-in user after validation.
         */
        post: operations["change_my_password_api_v1_users_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/soft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Soft Delete
         * @description Soft delete user account by setting is_deleted flag (Admin only).
         */
        delete: operations["soft_delete_api_v1_users__user_id__soft_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/hard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Hard Delete
         * @description Permanently delete user record from database (Admin only).
         */
        delete: operations["hard_delete_api_v1_users__user_id__hard_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * APIErrorDetail
         * @description Pydantic model representing structured error information in APIResponse.
         */
        APIErrorDetail: {
            /**
             * Code
             * @description Application-specific unique error code (e.g. NOT_FOUND, AI_EXECUTION_ERROR).
             */
            code: string;
            /**
             * Message
             * @description Human-readable error message for the user or developer.
             */
            message: string;
            /**
             * Details
             * @description Additional technical details or validation errors.
             */
            details?: {
                [key: string]: unknown;
            } | null;
        };
        /** APIResponse[InvitedEmailResponse] */
        APIResponse_InvitedEmailResponse_: {
            /**
             * Success
             * @description Indicates whether the operation was successful.
             */
            success: boolean;
            /** @description Payload returned on a successful operation. */
            data?: components["schemas"]["InvitedEmailResponse"] | null;
            /** @description Structured error details returned on failure. */
            error?: components["schemas"]["APIErrorDetail"] | null;
            /**
             * Meta
             * @description Response metadata (e.g., response time, timestamp).
             */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** APIResponse[List[UserResponse]] */
        APIResponse_List_UserResponse__: {
            /**
             * Success
             * @description Indicates whether the operation was successful.
             */
            success: boolean;
            /**
             * Data
             * @description Payload returned on a successful operation.
             */
            data?: components["schemas"]["UserResponse"][] | null;
            /** @description Structured error details returned on failure. */
            error?: components["schemas"]["APIErrorDetail"] | null;
            /**
             * Meta
             * @description Response metadata (e.g., response time, timestamp).
             */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** APIResponse[NoneType] */
        APIResponse_NoneType_: {
            /**
             * Success
             * @description Indicates whether the operation was successful.
             */
            success: boolean;
            /**
             * Data
             * @description Payload returned on a successful operation.
             */
            data?: null;
            /** @description Structured error details returned on failure. */
            error?: components["schemas"]["APIErrorDetail"] | null;
            /**
             * Meta
             * @description Response metadata (e.g., response time, timestamp).
             */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** APIResponse[TokenResponse] */
        APIResponse_TokenResponse_: {
            /**
             * Success
             * @description Indicates whether the operation was successful.
             */
            success: boolean;
            /** @description Payload returned on a successful operation. */
            data?: components["schemas"]["TokenResponse"] | null;
            /** @description Structured error details returned on failure. */
            error?: components["schemas"]["APIErrorDetail"] | null;
            /**
             * Meta
             * @description Response metadata (e.g., response time, timestamp).
             */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** APIResponse[UserResponse] */
        APIResponse_UserResponse_: {
            /**
             * Success
             * @description Indicates whether the operation was successful.
             */
            success: boolean;
            /** @description Payload returned on a successful operation. */
            data?: components["schemas"]["UserResponse"] | null;
            /** @description Structured error details returned on failure. */
            error?: components["schemas"]["APIErrorDetail"] | null;
            /**
             * Meta
             * @description Response metadata (e.g., response time, timestamp).
             */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** Body_analyze_document_api_v1_documents_analyze_post */
        Body_analyze_document_api_v1_documents_analyze_post: {
            /**
             * File
             * @description Analiz edilecek evrak dosyası.
             */
            file: string;
        };
        /**
         * ChatMessageRequest
         * @description Client request for a new chat interaction.
         */
        ChatMessageRequest: {
            /**
             * Message
             * @description Kullanıcının gönderdiği mesaj veya istek.
             */
            message: string;
            /**
             * Session Id
             * @description Opsiyonel oturum/sohbet kimliği. LangGraph checkpointer'ında thread_id olarak kullanılır: hem konuşma geçmişini hem de bekleyen bir insan-onayı kesintisini bu kimlik üzerinden taşır. Belirtilmezse sunucu bir tane üretir ve ilk SSE olayında (session) geri döner.
             */
            session_id?: string | null;
            /**
             * Document Id
             * @description Opsiyonel olarak hakkında soru sorulan spesifik belgenin (storage_path) ID'si.
             */
            document_id?: string | null;
            /**
             * @description Hız/kalite tercihi: fast (hızlı), balanced (dengeli, varsayılan), deep (derin muhakeme).
             * @default balanced
             */
            reasoning_level: components["schemas"]["ReasoningLevel"];
        };
        /**
         * ChatResumeRequest
         * @description Resume a chat run paused at the human-in-the-loop gate.
         *
         *     Two interrupt kinds share this one request shape: ``answer`` fills in a
         *     draft's missing-information placeholders (Görev 2's "eksik bilgi talep
         *     etme" requirement); ``approve``/``revise``/``reject`` resolve a draft
         *     that needed a human's sign-off before proceeding to unit routing.
         */
        ChatResumeRequest: {
            /**
             * Session Id
             * @description Devam ettirilecek oturumun thread_id'si.
             */
            session_id: string;
            /**
             * Action
             * @description answer: eksik bilgi cevapları. approve/revise/reject: taslak onay kararı.
             * @enum {string}
             */
            action: "answer" | "approve" | "revise" | "reject";
            /**
             * Answers
             * @description action='answer' için InfoQuestion.key -> kullanıcı cevabı eşlemesi.
             */
            answers?: {
                [key: string]: string;
            };
            /**
             * Instructions
             * @description action='revise' için ek talimat.
             * @default
             */
            instructions: string;
            /**
             * Reason
             * @description action='reject' için red gerekçesi.
             * @default
             */
            reason: string;
            /** @description action='revise' için bu tekrar denemede kullanılacak seviye. Belirtilmezse oturumun mevcut seviyesi korunur. */
            reasoning_level?: components["schemas"]["ReasoningLevel"] | null;
        };
        /**
         * CorrespondenceType
         * @description Supported official correspondence outputs produced by the draft workflow.
         * @enum {string}
         */
        CorrespondenceType: "cover_letter" | "response_letter" | "information_notice" | "other_official";
        /**
         * DocumentType
         * @description Types of incoming official documents (evrak) recognised at intake.
         *
         *     This taxonomy describes the document the institution *receives*. It is the
         *     counterpart of `CorrespondenceType`, which describes the official reply the
         *     institution *produces*. Keeping the two separate lets the intake pipeline
         *     classify an inbound petition while the drafting pipeline independently
         *     decides that the answer should be a response letter.
         * @enum {string}
         */
        DocumentType: "official_letter" | "petition" | "information_request" | "complaint" | "circular" | "directive" | "report" | "minutes" | "leave_request" | "other";
        /**
         * DraftClassificationSchema
         * @description The narrow slice of Görev 1's output the draft flow actually consumes.
         *
         *     Replaces ``DraftRequestSchema.classification: dict`` (was a free-form,
         *     unvalidated dict fed straight into prompts -- a correctness hole and an
         *     injection surface at once).
         */
        DraftClassificationSchema: {
            /** @description Gelen evrakın türü. */
            document_type: components["schemas"]["DocumentType"];
            /**
             * Document Type Label
             * @description Evrak türünün Türkçe adı.
             * @default
             */
            document_type_label: string;
            /**
             * Summary
             * @description Evrakın kısa Türkçe özeti.
             * @default
             */
            summary: string;
            fields?: components["schemas"]["EvrakField"];
            /** Missing Fields */
            missing_fields?: components["schemas"]["MissingField"][];
            /** Mevzuat References */
            mevzuat_references?: components["schemas"]["MevzuatReferenceSchema"][];
        };
        /**
         * DraftRequestSchema
         * @description Payload for initiating a drafting and routing workflow.
         */
        DraftRequestSchema: {
            /**
             * Storage Path
             * @description Ham evrakın saklandığı referans yol (Görev 1 çıktısından gelir).
             */
            storage_path: string;
            /** @description Görev 1'den elde edilen belge analiz ve sınıflandırma sonucu. */
            classification: components["schemas"]["DraftClassificationSchema"];
            /**
             * Instructions
             * @description Opsiyonel kullanıcı talimatı veya prompt eklemesi.
             * @default
             */
            instructions: string;
            /** @description Zorunlu tutulmak istenen yazışma türü. */
            correspondence_type?: components["schemas"]["CorrespondenceType"] | null;
            /**
             * @description Hız/kalite tercihi: fast (hızlı), balanced (dengeli, varsayılan), deep (derin muhakeme).
             * @default balanced
             */
            reasoning_level: components["schemas"]["ReasoningLevel"];
        };
        /**
         * EvrakField
         * @description Structured header and signature fields of an incoming official document.
         *
         *     Every field is optional and defaults to None on purpose: missing-field
         *     detection depends on the model reporting honest absence. A field given a
         *     meaningful default (for example a "Tasnif Dışı" confidentiality grade) would
         *     make every document look complete.
         */
        EvrakField: {
            /**
             * Sayi
             * @description Belgenin sayısı (örn. 'E-12345678-903-4567'). Yoksa null.
             */
            sayi?: string | null;
            /**
             * Tarih
             * @description Belgenin tarihi, belgede yazıldığı biçimde (örn. '30.07.2026'). Yoksa null.
             */
            tarih?: string | null;
            /**
             * Konu
             * @description Belgenin konusu. Yoksa null.
             */
            konu?: string | null;
            /**
             * Muhatap
             * @description Belgenin gönderildiği makam veya kişi (örn. 'İLGİLİ MAKAMA'). Yoksa null.
             */
            muhatap?: string | null;
            /**
             * Gonderen Kurum
             * @description Belgeyi gönderen idarenin adı (başlık/antet bilgisi). Yoksa null.
             */
            gonderen_kurum?: string | null;
            /**
             * Ilgi
             * @description İlgi bölümünde atıf yapılan belgeler. Yoksa boş liste.
             */
            ilgi?: string[];
            /**
             * Ekler
             * @description Belgenin ek listesinde sayılan belgeler. Yoksa boş liste.
             */
            ekler?: string[];
            /**
             * Imza Sahibi
             * @description İmza sahibinin adı ve soyadı. Yoksa null.
             */
            imza_sahibi?: string | null;
            /**
             * Imza Unvani
             * @description İmza sahibinin unvanı (örn. 'Genel Müdür'). Yoksa null.
             */
            imza_unvani?: string | null;
            /**
             * Gizlilik Derecesi
             * @description Gizlilik derecesi; yalnızca belgede açıkça yazıyorsa doldur (örn. 'Hizmete Özel'). Yoksa null.
             */
            gizlilik_derecesi?: string | null;
            /**
             * Ivedilik
             * @description İvedilik durumu; yalnızca belgede açıkça yazıyorsa doldur (örn. 'ACELE', 'GÜNLÜ'). Yoksa null.
             */
            ivedilik?: string | null;
            /**
             * Basvuran Adi
             * @description Dilekçe veya başvuruda başvuran kişinin adı ve soyadı. Yoksa null.
             */
            basvuran_adi?: string | null;
            /**
             * Adres
             * @description Başvuranın iş veya ikametgâh adresi. Yoksa null.
             */
            adres?: string | null;
            /**
             * Iletisim
             * @description Telefon veya e-posta gibi iletişim bilgisi. Yoksa null.
             */
            iletisim?: string | null;
            /**
             * Entities
             * @description Belgede geçen önemli varlık isimleri (Kişi, Kurum, Tarih, Para Birimi, Ürün, Referans vb.). Yoksa boş liste.
             */
            entities?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InvitedEmailCreate
         * @description Pydantic schema to whitelist/invite an email.
         */
        InvitedEmailCreate: {
            /**
             * Email
             * Format: email
             * @description Invited email address
             */
            email: string;
            /**
             * @description Pre-assigned role for the invitee
             * @default employee
             */
            role: components["schemas"]["UserRole"];
        };
        /**
         * InvitedEmailResponse
         * @description Pydantic schema returning whitelisted/invited email details.
         */
        InvitedEmailResponse: {
            /**
             * Id
             * @description Unique invitation ID
             */
            id: string;
            /**
             * Email
             * Format: email
             * @description Invited email address
             */
            email: string;
            /** @description Pre-assigned role */
            role: components["schemas"]["UserRole"];
            /**
             * Is Used
             * @description Invitation utilization status
             */
            is_used: boolean;
        };
        /**
         * LoginRequest
         * @description Pydantic schema for credentials validation on login.
         */
        LoginRequest: {
            /**
             * Username
             * @description Username or Email address of user
             */
            username: string;
            /**
             * Password
             * @description Raw account password
             */
            password: string;
        };
        /**
         * MevzuatReferenceSchema
         * @description A legislation reference suggested for the document.
         */
        MevzuatReferenceSchema: {
            /**
             * Mevzuat
             * @description Mevzuat adı ve varsa madde numarası.
             */
            mevzuat: string;
            /**
             * Aciklama
             * @description Bu hükmün evrakla ilişkisi.
             */
            aciklama: string;
        };
        /**
         * MissingField
         * @description A required field that is absent from the document, with its legal basis.
         */
        MissingField: {
            /**
             * Key
             * @description Eksik alanın teknik adı (örn. 'sayi').
             */
            key: string;
            /**
             * Label
             * @description Eksik alanın Türkçe adı (örn. 'Sayı').
             */
            label: string;
            /**
             * Severity
             * @description Alanın önemi: 'zorunlu' veya 'onerilen'.
             */
            severity: string;
            /**
             * Mevzuat
             * @description Alanı zorunlu kılan mevzuat ve madde atfı.
             */
            mevzuat: string;
            /**
             * Reason
             * @description Alanın neden gerekli olduğunun kısa Türkçe açıklaması.
             */
            reason: string;
        };
        /**
         * PasswordChangeRequest
         * @description Pydantic schema for updating current user's password securely.
         */
        PasswordChangeRequest: {
            /**
             * Current Password
             * @description The user's current password
             */
            current_password: string;
            /**
             * New Password
             * @description The user's new secure password
             */
            new_password: string;
        };
        /**
         * ReasoningLevel
         * @description Speed-vs-quality tradeoff requested for a single AI request.
         * @enum {string}
         */
        ReasoningLevel: "fast" | "balanced" | "deep";
        /**
         * RefreshRequest
         * @description Pydantic schema for access token renewal via refresh token.
         */
        RefreshRequest: {
            /**
             * Refresh Token
             * @description Long-lived JWT Refresh Token
             */
            refresh_token: string;
        };
        /**
         * RoutingSuggestionRequest
         * @description Request a unit-routing decision for a draft, independent of drafting it.
         */
        RoutingSuggestionRequest: {
            /**
             * Draft
             * @description Yönlendirilecek taslak veya evrak metni.
             */
            draft: string;
            /**
             * Confidence Score
             * @description Taslağın güven skoru; düşük skorlar insan onayına yönlendirir.
             * @default 100
             */
            confidence_score: number;
            /** @description Bağlam için evrak türü (opsiyonel). */
            document_type?: components["schemas"]["DocumentType"] | null;
        };
        /**
         * SensitivityLevel
         * @description Official Turkish document confidentiality grades (``gizlilik derecesi``).
         *
         *     Ordered from least to most restrictive so callers can compare levels
         *     directly (``level >= SensitivityLevel.GIZLI``). ``UNMARKED`` sits below
         *     ``TASNIF_DISI`` (the explicit "unclassified" grade) -- a document that
         *     never stated a grade at all is not the same fact as one that was
         *     positively marked unclassified, but neither blocks anything on its own.
         *
         *     ``rank`` is the same ordering as an int, because Qdrant payload filters
         *     compare numbers, not enum members: chunk/document metadata stores
         *     ``sensitivity_rank`` alongside this value's string for exactly that
         *     reason (see ``app.ai.retrieval`` range-filter wiring).
         * @enum {string}
         */
        SensitivityLevel: "unmarked" | "tasnif_disi" | "hizmete_ozel" | "ozel" | "gizli" | "cok_gizli";
        /**
         * TokenResponse
         * @description Pydantic schema for token response payload.
         */
        TokenResponse: {
            /**
             * Access Token
             * @description JWT Access Token
             */
            access_token: string;
            /**
             * Refresh Token
             * @description JWT Refresh Token
             */
            refresh_token: string;
            /**
             * Token Type
             * @description Token type prefix
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UserCreate
         * @description Pydantic schema for creating a new user account.
         *
         *     Deliberately has no ``clearance_level`` field: registration is
         *     self-service (gated only by the invite whitelist, no auth required), so
         *     letting a registrant set their own confidentiality ceiling would be a
         *     self-escalation hole. Every new account starts at
         *     ``UserModel.clearance_level``'s column default and can only be raised
         *     afterwards by an admin via ``PUT /users/{id}``.
         */
        UserCreate: {
            /**
             * Username
             * @description Unique username
             */
            username: string;
            /**
             * Email
             * Format: email
             * @description Unique email address
             */
            email: string;
            /**
             * Password
             * @description Plain text password
             */
            password: string;
            /**
             * @description Assigned role for authorization
             * @default employee
             */
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserResponse
         * @description Pydantic schema for user account details output.
         */
        UserResponse: {
            /**
             * Id
             * @description Unique user ID
             */
            id: string;
            /**
             * Username
             * @description Unique username
             */
            username: string;
            /**
             * Email
             * Format: email
             * @description Unique email address
             */
            email: string;
            /** @description Assigned authorization role */
            role: components["schemas"]["UserRole"];
            /** @description Confidentiality ceiling (EMPLOYEE role only). */
            clearance_level: components["schemas"]["SensitivityLevel"];
            /**
             * Is Active
             * @description Status of user account
             */
            is_active: boolean;
            /**
             * Is Deleted
             * @description Soft deletion flag status
             */
            is_deleted: boolean;
        };
        /**
         * UserRole
         * @description User role types used throughout the system for RBAC.
         *
         *     ADMIN and MANAGER both clear every confidentiality level (see
         *     ``GuardrailPolicy.role_clearance_map``) -- MANAGER represents a company
         *     manager, trusted with full access the same as ADMIN. EMPLOYEE's ceiling
         *     is not fixed by role at all: it comes from that individual's own
         *     ``UserModel.clearance_level``, since two employees can legitimately need
         *     different access.
         * @enum {string}
         */
        UserRole: "admin" | "manager" | "employee";
        /**
         * UserUpdate
         * @description Pydantic schema for updating a user account.
         */
        UserUpdate: {
            /**
             * Email
             * @description Optional updated email address
             */
            email?: string | null;
            /** @description Optional updated authorization role */
            role?: components["schemas"]["UserRole"] | null;
            /**
             * Is Active
             * @description Optional updated status of user account
             */
            is_active?: boolean | null;
            /** @description Optional updated confidentiality ceiling (EMPLOYEE role only -- ADMIN/MANAGER clear everything regardless of this value). Admin-only, same as role/is_active. */
            clearance_level?: components["schemas"]["SensitivityLevel"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_api_v1_health_get: {
        parameters: {
            query?: {
                deep?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_TokenResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_TokenResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_chat_message_api_v1_chat_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_chat_message_api_v1_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_chat_stream_api_v1_chat_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_chat_sync_api_v1_chat_resume_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chat_sessions_api_v1_chat_sessions_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chat_session_messages_api_v1_chat_sessions__session_id__messages_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_state_api_v1_chat_sessions__session_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_document_api_v1_documents_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_document_api_v1_documents_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_draft_api_v1_documents_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRequestSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_correspondence_types_api_v1_documents_correspondence_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_document_analysis_api_v1_documents__storage_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storage_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drafts_api_v1_drafts_get: {
        parameters: {
            query?: {
                session_id?: string | null;
                document_id?: string | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_v1_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_draft_versions_api_v1_drafts__draft_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_routing_api_v1_routing_suggest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutingSuggestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                role?: components["schemas"]["UserRole"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_List_UserResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_UserResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_user_api_v1_users_invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitedEmailCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_InvitedEmailResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_UserResponse_"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_UserResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_UserResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_my_password_api_v1_users_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    soft_delete_api_v1_users__user_id__soft_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hard_delete_api_v1_users__user_id__hard_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
