"""documents analysis table

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-04 23:16:26.695645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('extractor', sa.String(length=64), nullable=False),
    sa.Column('used_ocr', sa.Boolean(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('document_type_label', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=False),
    sa.Column('mevzuat_references', sa.JSON(), nullable=False),
    sa.Column('scrubbed_markers', sa.JSON(), nullable=False),
    sa.Column('compliance_status', sa.String(length=32), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('storage_path')
    )
    op.create_index(op.f('ix_documents_compliance_status'), 'documents', ['compliance_status'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_compliance_status'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
