export const queryKeys = {
  currentUser: ["current-user"] as const,
  documents: (page = 1) => ["documents", page] as const,
  documentAnalysis: (storagePath: string) => ["documents", "analysis", storagePath] as const,
  documentText: (storagePath: string) => ["documents", "text", storagePath] as const,
  chatSessions: (page = 1) => ["chat-sessions", page] as const,
  chatMessages: (sessionId: string, page = 1) => ["chat-messages", sessionId, page] as const,
  chatState: (sessionId: string) => ["chat-state", sessionId] as const,
  drafts: (page = 1) => ["drafts", page] as const,
  draft: (draftId: string) => ["draft", draftId] as const,
  draftVersions: (draftId: string) => ["draft", draftId, "versions"] as const,
  routing: ["routing-suggestion"] as const,
  users: ["admin-users"] as const,
  health: (deep: boolean) => ["health", deep ? "deep" : "normal"] as const,
  trainingSamples: (companyId: string, page = 1) => ["training-samples", companyId, page] as const,
  trainingStats: (companyId: string) => ["training-stats", companyId] as const,
  trainingRuns: (companyId: string, page = 1) => ["training-runs", companyId, page] as const,
  conversations: ["conversations"] as const,
  conversationMessages: (conversationId: string) => ["conversation-messages", conversationId] as const,
  favorites: ["favorites"] as const,
  userSearch: (q: string, unitId: string, role: string) => ["user-search", q, unitId, role] as const,
  notifications: (unreadOnly: boolean, page = 1) => ["notifications", unreadOnly, page] as const,
  units: ["units"] as const,
  transfer: (transferId: string) => ["transfer", transferId] as const,
  transferRecommendations: (draftId: string) => ["transfer-recommendations", draftId] as const,
  knowledgeGraph: ["documents", "graph"] as const,
  documentGraph: (storagePath: string) => ["documents", "graph", storagePath] as const,
};
